language: java
jdk: openjdk8

sudo: required
dist: trusty

before_install:
  - sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
  - sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
  - ip addr # for confirmation. can be skipped

branches:
  only:
  - master
  - development
  - /hotfix.*/

addons:
  sonarcloud:
    organization: "giscience"

git:
    depth: false # required for sonarcloud

script:
  - cp ${TRAVIS_BUILD_DIR}/openrouteservice-api-tests/conf/app.config.test ${TRAVIS_BUILD_DIR}/openrouteservice/src/main/resources/app.config
  - mvn -f ${TRAVIS_BUILD_DIR}/openrouteservice/pom.xml dependency:resolve dependency:resolve-plugins -B
  - if [[ "$TRAVIS_PULL_REQUEST" == "false" || \
         "$TRAVIS_PULL_REQUEST_SLUG" == "$TRAVIS_REPO_SLUG" ]];
    then
        mvn -f ${TRAVIS_BUILD_DIR}/openrouteservice/pom.xml org.jacoco:jacoco-maven-plugin:prepare-agent verify sonar:sonar -B;
    else
        mvn -f ${TRAVIS_BUILD_DIR}/openrouteservice/pom.xml verify -B;
    fi

notifications:
  webhooks: https://chat.gistools.geog.uni-heidelberg.de/hooks/fqX555ZPxYFdHeqhS/2kxt4rNATiJ9cB8pLmkSc2R3mrxnmJrEQZFd7JKqiPEGFnW9
